[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "none"
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
  "v4-core/=lib/v4-periphery/lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
]

[lint]
exclude_lints = ["block-timestamp"]

[fuzz]
runs = 256
